fix: disable precompiled headers in llvm (#43)
Gives a lot of errors
```
[LLVM] Running clang-tidy on Clang codebase...
Running clang-tidy in 32 threads for 1049 files out of 4067 in compilation database ...
[   1/1049][0.0s] /__w/CTIT/CTIT/llvm-project/build/bin/clang-tidy -checks=-*,performance-string-view-conversions -p=/__w/CTIT/CTIT/llvm-project/build -quiet /__w/CTIT/CTIT/llvm-project/clang/lib/AST/Expr.cpp
error: PCH file '/__w/CTIT/CTIT/llvm-project/build/lib/Support/CMakeFiles/LLVMSupport.dir/cmake_pch.hxx.pch' uses an older format that is no longer supported [clang-diagnostic-error]
Error while processing /__w/CTIT/CTIT/llvm-project/clang/lib/AST/Expr.cpp.

[   2/1049][0.0s] /__w/CTIT/CTIT/llvm-project/build/bin/clang-tidy -checks=-*,performance-string-view-conversions -p=/__w/CTIT/CTIT/llvm-project/build -quiet /__w/CTIT/CTIT/llvm-project/clang/lib/AST/ASTTypeTraits.cpp
error: PCH file '/__w/CTIT/CTIT/llvm-project/build/lib/Support/CMakeFiles/LLVMSupport.dir/cmake_pch.hxx.pch' uses an older format that is no longer supported [clang-diagnostic-error]
Error while processing /__w/CTIT/CTIT/llvm-project/clang/lib/AST/ASTTypeTraits.cpp.
```

PCH were introduced recently in
https://github.com/llvm/llvm-project/pull/176420